# Marker used by CI/analyzers to find Android project root
android.project.root=android_flutter_frontend
android.settings.file=android_flutter_frontend/settings.gradle.dcl
android.wrapper=android_flutter_frontend/gradlew
android.modules=app,list,utilities
