android.project.root=android_flutter_frontend
android.gradle.settings=android_flutter_frontend/settings.gradle.dcl
android.wrapper.unix=android_flutter_frontend/gradlew
android.wrapper.windows=android_flutter_frontend/gradlew.bat
